import React, { useState, useEffect, useRef } from "react";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  Title,
  Tooltip,
  Legend,
  Filler,
  ArcElement
} from "chart.js";
import { Line, Bar, Doughnut } from "react-chartjs-2";
import toast from 'react-hot-toast';
import { useTheme } from "../../context/ThemeContext";
import { useGlobalContext } from "../../context/GlobalContext";
import { useNavigate } from "react-router-dom";
import { pdf, Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer';
import logo from "../../assets/logo.png"

// Register ChartJS components
ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  Title,
  Tooltip,
  Legend,
  Filler,
  ArcElement
);


// --- PDF STYLES ---
const pdfStyles = StyleSheet.create({
  page: { padding: 40, backgroundColor: '#FFFFFF', fontFamily: 'Helvetica' },
  header: { marginBottom: 20, borderBottomWidth: 1, borderBottomColor: '#8c0000', paddingBottom: 10, display:"flex", flexDirection:"row", gap:10 },
  title: { fontSize: 24, fontWeight: 'bold' },
  date: { fontSize: 10, color: '#666', marginTop: 4 },
  section: { marginTop: 20 },
  sectionTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 10, color: '#111' },
  statsRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20, backgroundColor: '#F9FAFB', padding: 15, borderRadius: 10 },
  statBox: { textAlign: 'center' },
  statLabel: { fontSize: 10, color: '#666' },
  statValue: { fontSize: 16, fontWeight: 'bold', marginTop: 2 },
  chartImage: { width: '100%', height: 200, objectFit: 'contain', marginVertical: 10 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', fontSize: 10, color: '#999' },
  logo: { width: 50, height:40 }
});

// --- PDF COMPONENT ---
const ProgressReportPDF = ({ stats, chartImages, dietInfo, adherenceInfo, dateInfo }) => (
  <Document>
    <Page size="A4" style={pdfStyles.page}>
      <View style={pdfStyles.header}>
        <Image src={logo} style={pdfStyles.logo} />
        <View>
          <Text style={pdfStyles.title}>Songar's GYM</Text>
          <Text style={pdfStyles.date}>Report Period: {dateInfo}</Text>
        </View>
      </View>

      <View style={pdfStyles.statsRow}>
        <View style={pdfStyles.statBox}>
          <Text style={pdfStyles.statLabel}>START WEIGHT</Text>
          <Text style={pdfStyles.statValue}>{stats.startWeight} kg</Text>
        </View>
        <View style={pdfStyles.statBox}>
          <Text style={pdfStyles.statLabel}>CURRENT WEIGHT</Text>
          <Text style={pdfStyles.statValue}>{stats.currentWeight} kg</Text>
        </View>
        <View style={pdfStyles.statBox}>
          <Text style={pdfStyles.statLabel}>SESSIONS DONE</Text>
          <Text style={pdfStyles.statValue}>{stats.sessionsDone}</Text>
        </View>
        <View style={pdfStyles.statBox}>
          <Text style={pdfStyles.statLabel}>AVG ADHERENCE</Text>
          <Text style={pdfStyles.statValue}>{stats.avgAdherence}%</Text>
        </View>
      </View>

      {chartImages.weight && (
        <View style={pdfStyles.section}>
          <Text style={pdfStyles.sectionTitle}>Weight Progression</Text>
          <Image src={chartImages.weight} style={pdfStyles.chartImage} />
        </View>
      )}

      {chartImages.adherence && (
        <View style={pdfStyles.section}>
          <Text style={pdfStyles.sectionTitle}>Weekly Adherence</Text>
          <Image src={chartImages.adherence} style={pdfStyles.chartImage} />
        </View>
      )}

      {chartImages.consistency && (
        <View style={pdfStyles.section}>
          <Text style={pdfStyles.sectionTitle}>Workout & Diet Consistency by Day</Text>
          <Image src={chartImages.consistency} style={pdfStyles.chartImage} />
        </View>
      )}

      <Text style={pdfStyles.footer}>Generated by Gym Management System for Santosh</Text>
    </Page>
  </Document>
);

const Progress = () => {
  const { api, BACKEND_URL, loadingIMG} = useGlobalContext();
  const { colors, theme } = useTheme();
  const navigate = useNavigate();

  // --- REFS FOR CHARTS ---
  const weightChartRef = useRef(null);
  const consistencyChartRef = useRef(null);
  const dietChartRef = useRef(null);
  const adherenceChartRef = useRef(null);

  // --- STATE ---
  const [weightHistory, setWeightHistory] = useState([]);
  const [progressLog, setProgressLog] = useState([]);
  const [memberStats, setMemberStats] = useState({
    startWeight: 0,
    currentWeight: 0,
    goalWeight: 0,
    attendance: 0
  });
  const [loading, setLoading] = useState(true);
  const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth());
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        const userInfo = JSON.parse(localStorage.getItem("userInfo"));
        const token = userInfo?.token;

        const profileRes = await fetch(`${BACKEND_URL}/api/members/profile`, {
          headers: { Authorization: `Bearer ${token}` }
        });
        const profileData = await profileRes.json();

        const progressRes = await fetch(`${BACKEND_URL}/api/workout-diet/my/plan`, {
          headers: { Authorization: `Bearer ${token}` }
        });
        const progressDataRaw = await progressRes.json();

        if (progressDataRaw) {
          const sortedWeightHistory = (progressDataRaw.weightHistory || []).sort((a, b) => new Date(a.date) - new Date(b.date));
          setWeightHistory(sortedWeightHistory);
          setProgressLog(progressDataRaw.progress || []);
        }

        if (profileData) {
          const startWeight = profileData.startWeight || (progressDataRaw.weightHistory?.[0]?.weight) || profileData.currentWeight || 0;
          setMemberStats({
            startWeight: startWeight,
            currentWeight: profileData.currentWeight || 0,
            goalWeight: profileData.targetWeight || 0,
            attendance: 0
          });
        }
      } catch (err) {
        console.error(err);
        toast.error("Failed to load progress data");
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, [BACKEND_URL]);

  // --- CHART DATA PREP ---
  const getWeightChartData = () => {
    let labels = [];
    let data = [];
    if (memberStats.startWeight) {
      labels.push("Start");
      data.push(memberStats.startWeight);
    }
    weightHistory.forEach(log => {
      labels.push(new Date(log.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }));
      data.push(log.weight);
    });
    if (memberStats.currentWeight && (data.length === 0 || data[data.length - 1] !== memberStats.currentWeight)) {
      labels.push("Current");
      data.push(memberStats.currentWeight);
    }
    return { labels, data };
  };

  const weightChartInfo = getWeightChartData();
  const weightChartData = {
    labels: weightChartInfo.labels,
    datasets: [{
      label: "Weight (kg)",
      data: weightChartInfo.data,
      borderColor: colors.primary,
      backgroundColor: "rgba(217, 241, 127, 0.2)",
      tension: 0.3,
      fill: true,
      pointBackgroundColor: colors.card,
      pointBorderColor: colors.primary,
      pointBorderWidth: 2,
      pointRadius: 5,
    }],
  };

  const filteredLogs = progressLog.filter(log => {
    const logDate = new Date(log.date);
    return log.workoutCompleted === true &&
      logDate.getMonth() === selectedMonth &&
      logDate.getFullYear() === selectedYear;
  });

  const daysOfWeek = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
  const workoutCounts = new Array(7).fill(0);
  filteredLogs.forEach(log => {
    const date = new Date(log.date);
    let dayIndex = date.getDay();
    let chartIndex = dayIndex === 0 ? 6 : dayIndex - 1;
    workoutCounts[chartIndex]++;
  });

  // Calculate adherence percentages
  const totalProgress = progressLog.length || 1;
  const workoutCompleted = progressLog.filter(p => p.workoutCompleted).length;
  const dietCompleted = progressLog.filter(p => p.dietCompleted).length;
  const workoutAdherence = Math.round((workoutCompleted / totalProgress) * 100);
  const dietAdherence = Math.round((dietCompleted / totalProgress) * 100);
  const avgAdherence = Math.round((workoutAdherence + dietAdherence) / 2);

  // Weekly Adherence Chart Data
  const adherenceChartData = {
    labels: ["Workout", "Diet"],
    datasets: [{
      label: "Adherence %",
      data: [workoutAdherence, dietAdherence],
      backgroundColor: ["#CDE7FE", "#FEEF75"],
      borderRadius: 8,
      barThickness: 40,
    }],
  };

  // Workout & Diet Consistency by Day
  const dietCounts = new Array(7).fill(0);
  progressLog.forEach(log => {
    const date = new Date(log.date);
    const logMonth = date.getMonth();
    const logYear = date.getFullYear();
    
    if (logMonth === selectedMonth && logYear === selectedYear) {
      let dayIndex = date.getDay();
      let chartIndex = dayIndex === 0 ? 6 : dayIndex - 1;
      if (log.dietCompleted) {
        dietCounts[chartIndex]++;
      }
    }
  });

  const consistencyData = {
    labels: daysOfWeek,
    datasets: [
      {
        label: "Workouts",
        data: workoutCounts,
        backgroundColor: theme === 'dark' ? colors.secondary : '#1f2937',
        borderRadius: 6,
        barThickness: 16,
      },
      {
        label: "Diet",
        data: dietCounts,
        backgroundColor: "#FEEF75",
        borderRadius: 6,
        barThickness: 16,
      }
    ],
  };

  const dietTotal = progressLog.length;
  const dietSuccess = progressLog.filter(l => l.dietCompleted).length;
  const dietPercentage = dietTotal > 0 ? Math.round((dietSuccess / dietTotal) * 100) : 0;

  const dietChartData = {
    labels: ["Adherence", "Missed"],
    datasets: [{
      data: [dietPercentage, 100 - dietPercentage],
      backgroundColor: ["#D5EBFE", theme === 'dark' ? '#374151' : '#f3f4f6'],
      borderWidth: 0,
    }],
  };

  // --- DOWNLOAD PDF LOGIC ---
  const handleDownloadReport = async () => {
    const loadingToast = toast.loading("Generating your PDF report...");
    try {
      // Capture chart images from canvas
      const weightImage = weightChartRef.current?.toBase64Image();
      const consistencyImage = consistencyChartRef.current?.toBase64Image();
      const dietImage = dietChartRef.current?.toBase64Image();
      const adherenceImage = adherenceChartRef.current?.toBase64Image();

      const blob = await pdf(
        <ProgressReportPDF
          stats={{
            ...memberStats,
            sessionsDone: workoutCompleted,
            avgAdherence: avgAdherence
          }}
          chartImages={{ 
            weight: weightImage, 
            consistency: consistencyImage, 
            diet: dietImage,
            adherence: adherenceImage 
          }}
          dietInfo={{ percentage: dietPercentage, success: dietSuccess, total: dietTotal }}
          adherenceInfo={{ workout: workoutAdherence, diet: dietAdherence }}
          dateInfo={`${getMonthName(selectedMonth)} ${selectedYear}`}
        />
      ).toBlob();

      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `Fitness_Report_Santosh_${selectedYear}_${selectedMonth + 1}.pdf`;
      link.click();

      toast.dismiss(loadingToast);
      toast.success("Report downloaded successfully!");
    } catch (error) {
      console.error("PDF Generation Error:", error);
      toast.dismiss(loadingToast);
      toast.error("Failed to generate PDF report.");
    }
  };

  const handleRequestReview = () => navigate('/member/chat');
  const getMonthName = (monthIndex) => new Date(2000, monthIndex, 1).toLocaleString('default', { month: 'long' });

  if (loading) {
      return (
         <div className="fixed inset-0 flex items-center justify-center h-screen" style={{ color: colors.textMuted }}>
            <img src={loadingIMG} className='h-20 w-25'/>
         </div>
      );
   }

  return (
    <div className="w-full max-w-6xl mx-auto space-y-8 pb-10 font-sans px-4 sm:px-0">
      {/* HEADER */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-4">
        <div>
          
          <p className="text-sm md:text-base mt-1" style={{ color: colors.textMuted }}>Track your fitness journey and milestones.</p>
        </div>
      </div>

      {/* TOP SUMMARY CARDS - 4 Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="rounded-xl p-4 border shadow-sm" style={{ backgroundColor: colors.card, borderColor: colors.border }}>
          <p className="text-xs font-bold uppercase mb-1" style={{ color: colors.textMuted }}>Current Weight</p>
          <p className="text-xl font-black" style={{ color: colors.text }}>
            {memberStats.currentWeight} <span className="text-sm font-bold" style={{ color: colors.textMuted }}>kg</span>
          </p>
        </div>
        <div className="rounded-xl p-4 border shadow-sm" style={{ backgroundColor: colors.card, borderColor: colors.border }}>
          <p className="text-xs font-bold uppercase mb-1" style={{ color: colors.textMuted }}>Start Weight</p>
          <p className="text-xl font-black" style={{ color: colors.text }}>
            {memberStats.startWeight} <span className="text-sm font-bold" style={{ color: colors.textMuted }}>kg</span>
          </p>
        </div>
        <div className="rounded-xl p-4 border shadow-sm" style={{ backgroundColor: colors.card, borderColor: colors.border }}>
          <p className="text-xs font-bold uppercase mb-1" style={{ color: colors.textMuted }}>Sessions Done</p>
          <p className="text-xl font-black" style={{ color: colors.text }}>{workoutCompleted}</p>
        </div>
        <div className="rounded-xl p-4 border shadow-sm" style={{ backgroundColor: colors.card, borderColor: colors.border }}>
          <p className="text-xs font-bold uppercase mb-1" style={{ color: colors.textMuted }}>Avg Adherence</p>
          <p className="text-xl font-black" style={{ color: colors.text }}>{avgAdherence}%</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* LEFT COL: Weight Trend */}
        <div className="lg:col-span-2 space-y-6">
          {/* Weight Progression Chart */}
          <div className="rounded-[2.5rem] p-6 md:p-8 border shadow-sm relative overflow-hidden"
            style={{ backgroundColor: colors.card, borderColor: colors.border }}>
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-lg font-bold" style={{ color: colors.text }}>Weight Progression</h3>
            </div>
            <div className="h-64 w-full">
              <Line
                ref={weightChartRef}
                data={weightChartData}
                options={{
                  responsive: true,
                  maintainAspectRatio: false,
                  animation: false,
                  plugins: { legend: { display: false } },
                  scales: {
                    y: { ticks: { color: colors.textMuted }, grid: { color: colors.border } },
                    x: { ticks: { color: colors.textMuted }, grid: { display: false } }
                  }
                }}
              />
            </div>
          </div>

          {/* Weekly Adherence Chart */}
          <div className="rounded-[2.5rem] p-6 md:p-8 border shadow-sm"
            style={{ backgroundColor: colors.card, borderColor: colors.border }}>
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-lg font-bold" style={{ color: colors.text }}>Weekly Adherence</h3>
            </div>
            <div className="h-48 w-full">
              <Bar
                ref={adherenceChartRef}
                data={adherenceChartData}
                options={{
                  responsive: true,
                  maintainAspectRatio: false,
                  animation: false,
                  plugins: { 
                    legend: { display: false },
                    tooltip: {
                      callbacks: {
                        label: function(context) {
                          return context.parsed.y + '%';
                        }
                      }
                    }
                  },
                  scales: { 
                    y: { 
                      beginAtZero: true, 
                      max: 100,
                      ticks: { 
                        color: colors.textMuted,
                        callback: function(value) {
                          return value + '%';
                        }
                      }, 
                      grid: { color: colors.border } 
                    }, 
                    x: { ticks: { color: colors.textMuted }, grid: { display: false } } 
                  }
                }}
              />
            </div>
          </div>

          {/* Workout & Diet Consistency by Day */}
          <div className="rounded-[2.5rem] p-6 md:p-8 border shadow-sm"
            style={{ backgroundColor: colors.card, borderColor: colors.border }}>
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-6 gap-3 sm:gap-0">
              <h3 className="text-lg font-bold" style={{ color: colors.text }}>Workout & Diet Consistency by Day</h3>
              <div className="flex gap-2">
                <select
                  value={selectedMonth}
                  onChange={(e) => setSelectedMonth(Number(e.target.value))}
                  className="border rounded-lg text-xs font-bold px-3 py-1.5 focus:outline-none cursor-pointer"
                  style={{ backgroundColor: colors.background, color: colors.text, borderColor: colors.border }}
                >
                  {Array.from({ length: 12 }, (_, i) => (
                    <option key={i} value={i}>{getMonthName(i)}</option>
                  ))}
                </select>
                <select
                  value={selectedYear}
                  onChange={(e) => setSelectedYear(Number(e.target.value))}
                  className="border rounded-lg text-xs font-bold px-3 py-1.5 focus:outline-none cursor-pointer"
                  style={{ backgroundColor: colors.background, color: colors.text, borderColor: colors.border }}
                >
                  <option value={2025}>2025</option>
                  <option value={2026}>2026</option>
                </select>
              </div>
            </div>
            <div className="h-48 w-full">
              <Bar
                ref={consistencyChartRef}
                data={consistencyData}
                options={{
                  responsive: true,
                  maintainAspectRatio: false,
                  animation: false,
                  plugins: { 
                    legend: { 
                      display: true,
                      position: 'bottom',
                      labels: {
                        color: colors.textMuted,
                        usePointStyle: true,
                        padding: 15
                      }
                    } 
                  },
                  scales: { 
                    y: { 
                      ticks: { color: colors.textMuted }, 
                      grid: { color: colors.border } 
                    }, 
                    x: { 
                      ticks: { color: colors.textMuted }, 
                      grid: { display: false } 
                    } 
                  }
                }}
              />
            </div>
          </div>
        </div>

        {/* RIGHT COL: Stats & Diet */}
        <div className="space-y-6">
          <div className="rounded-[2.5rem] p-6 md:p-8 border shadow-sm text-center relative"
            style={{ backgroundColor: colors.card, borderColor: colors.border }}>
            <h3 className="text-lg font-bold mb-6" style={{ color: colors.text }}>Diet Adherence</h3>
            <div className="w-40 h-40 mx-auto relative">
              <Doughnut
                ref={dietChartRef}
                data={dietChartData}
                options={{ cutout: '75%', plugins: { legend: { display: false } }, animation: false }}
              />
              <div className="absolute inset-0 flex items-center justify-center flex-col">
                <span className="text-3xl font-black" style={{ color: colors.text }}>{dietPercentage}%</span>
                <span className="text-xs font-bold uppercase" style={{ color: colors.textMuted }}>Success</span>
              </div>
            </div>
          </div>

          <div className="rounded-[2.5rem] p-6 md:p-8 border relative overflow-hidden"
            style={{
              backgroundColor: theme === 'dark' ? 'rgba(6, 78, 59, 0.2)' : '#f0fdf4',
              borderColor: theme === 'dark' ? '#064e3b' : '#dcfce7'
            }}>
            <h3 className="text-lg font-bold mb-3 flex items-center gap-2 relative z-10" style={{ color: theme === 'dark' ? '#86efac' : '#14532d' }}>
              <i className="fa-solid fa-user-pen"></i> Trainer's Note
            </h3>
            <p className="italic leading-relaxed text-sm mb-4 relative z-10" style={{ color: theme === 'dark' ? '#bbf7d0' : '#166534' }}>
              "Great progress on the weight lifting! Try to increase protein intake slightly next week."
            </p>
            <p className="text-xs font-medium text-right" style={{ color: theme === 'dark' ? '#4ade80' : '#16a34a' }}>Updated: {new Date().toLocaleDateString()}</p>
          </div>
        </div>
      </div>

      {/* ACTION FOOTER */}
      <div className="rounded-[2rem] p-6 flex flex-col md:flex-row justify-between items-center gap-4 text-center md:text-left"
        style={{ backgroundColor: theme === 'dark' ? '#1f2937' : '#f9fafb' }}>
        <div className="text-sm" style={{ color: colors.textMuted }}>
          Need detailed insights or advice?
        </div>
        <div className="flex flex-col sm:flex-row gap-4 w-full md:w-auto">
          <button
            onClick={handleRequestReview}
            className="flex-1 px-6 py-3 border rounded-xl text-sm font-bold transition-colors shadow-sm flex items-center justify-center gap-2 cursor-pointer"
            style={{ backgroundColor: colors.card, borderColor: colors.border, color: colors.textMuted }}
          >
            <i className="fa-regular fa-paper-plane"></i> Ask Trainer
          </button>
          <button
            onClick={handleDownloadReport}
            className="flex-1 px-6 py-3 rounded-xl text-sm font-bold transition-colors shadow-lg hover:shadow-xl cursor-pointer"
            style={{ backgroundColor: colors.primary, color: '#14532d' }}
          >
            Download Report
          </button>
        </div>
      </div>
    </div>
  );
};

export default Progress;